spring.application.name=hiltech-spring-modulith-spike
spring.datasource.url=jdbc:h2:mem:hiltech-spike;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
spring.modulith.events.jdbc.schema-initialization.enabled=true
spring.modulith.events.republish-outstanding-events-on-restart=false
