package com.hiltech.shared.core.work

import kotlinx.serialization.Serializable

@Serializable data class CreateWorkOrderRequestDto(val operationId:String,val siteId:String,val projectSiteId:String,val areaId:String?=null,val workPackageId:String?=null,val explicitCode:String?=null,val workTypeCode:String,val workTypeRevision:Int?=null,val title:String,val description:String?=null,val plannedStart:String?=null,val plannedEnd:String?=null,val priorityCode:String?=null,val baseProjectVersion:Long,val expectedBaselineVersion:Int,val clientOccurredAt:String)
@Serializable data class UpdateWorkOrderRequestDto(val operationId:String,val areaId:String?=null,val workPackageId:String?=null,val title:String,val description:String?=null,val plannedStart:String?=null,val plannedEnd:String?=null,val priorityCode:String,val baseVersion:Long,val clientOccurredAt:String)
@Serializable data class PlanWorkRequestDto(val operationId:String,val workTypeCode:String,val workTypeRevision:Int?=null,val payloadSchemaVersion:Int=1,val structuredInstructionJson:String?=null,val instructionSummary:String?=null,val baseVersion:Long,val expectedBaselineVersion:Int,val clientOccurredAt:String)
@Serializable data class ReviseInstructionRequestDto(val operationId:String,val payloadSchemaVersion:Int,val structuredInstructionJson:String,val summary:String?=null,val changeReason:String,val baseVersion:Long,val clientOccurredAt:String)
@Serializable data class CreateWorkTaskRequestDto(val operationId:String,val taskCode:String?=null,val title:String,val description:String?=null,val sortOrder:Int=0,val mandatory:Boolean=true,val estimatedDurationMinutes:Int?=null,val evidenceRequirementKey:String?=null,val baseVersion:Long,val clientOccurredAt:String)
@Serializable data class UpdateWorkTaskRequestDto(val operationId:String,val taskCode:String?=null,val title:String,val description:String?=null,val sortOrder:Int=0,val mandatory:Boolean=true,val estimatedDurationMinutes:Int?=null,val evidenceRequirementKey:String?=null,val state:String,val baseTaskVersion:Long,val baseWorkOrderVersion:Long,val clientOccurredAt:String)
@Serializable data class AddWorkDependencyRequestDto(val operationId:String,val predecessorWorkOrderId:String,val dependencyType:String="FINISH_TO_START",val lagMinutes:Long=0,val baseVersion:Long,val clientOccurredAt:String)
@Serializable data class RemoveWorkDependencyRequestDto(val operationId:String,val baseVersion:Long,val baseDependencyVersion:Long,val clientOccurredAt:String)
@Serializable data class ActivateProjectRequestDto(val operationId:String,val baseVersion:Long,val expectedBaselineVersion:Int,val clientOccurredAt:String)

@Serializable data class ConfigRefDto(val id:String,val code:String,val name:String,val revision:Int)
@Serializable data class WorkBindingDto(val bindingId:String,val bindingRevision:Int,val workType:ConfigRefDto,val assignmentPolicy:ConfigRefDto,val readinessPolicy:ConfigRefDto,val evidencePolicy:ConfigRefDto,val reviewPolicy:ConfigRefDto,val trackingPolicy:ConfigRefDto?=null,val checklistTemplate:ConfigRefDto?=null,val instructionTemplate:ConfigRefDto?=null,val createdAt:String)
@Serializable data class WorkInstructionDto(val instructionRevisionId:String,val revision:Int,val sourceTemplate:ConfigRefDto?=null,val payloadSchemaVersion:Int,val structuredPayloadJson:String,val summary:String?=null,val changeReason:String?=null,val createdAt:String,val correlationId:String)
@Serializable data class ChecklistItemDto(val itemId:String,val itemKey:String,val label:String,val required:Boolean,val sortOrder:Int,val completionState:String,val evidenceRequirementKey:String?=null,val version:Long)
@Serializable data class RequirementDto(val requirementId:String,val family:String,val key:String,val sourceConfig:ConfigRefDto?=null,val required:Boolean,val satisfactionState:String,val version:Long)
@Serializable data class WorkTaskDto(val taskId:String,val taskCode:String?=null,val title:String,val description:String?=null,val sortOrder:Int,val mandatory:Boolean,val estimatedDurationMinutes:Int?=null,val evidenceRequirementKey:String?=null,val state:String,val version:Long)
@Serializable data class WorkDependencyDto(val dependencyId:String,val predecessorWorkOrderId:String,val successorWorkOrderId:String,val dependencyType:String,val lagMinutes:Long,val version:Long)
@Serializable data class WorkOrderDto(val workOrderId:String,val organizationId:String,val workOrderCode:String,val projectId:String,val siteId:String,val projectSiteId:String,val areaId:String?=null,val workPackageId:String?=null,val title:String,val description:String?=null,val lifecycleState:String,val readinessState:String,val plannedStart:String?=null,val plannedEnd:String?=null,val priorityCode:String,val countsTowardProjectProgress:Boolean,val progressWeight:String,val baselineVersion:Int,val createdAt:String,val updatedAt:String,val version:Long,val binding:WorkBindingDto?=null,val instruction:WorkInstructionDto?=null,val checklist:List<ChecklistItemDto> = emptyList(),val requirements:List<RequirementDto> = emptyList(),val tasks:List<WorkTaskDto> = emptyList(),val dependencies:List<WorkDependencyDto> = emptyList())
@Serializable data class WorkOrderMutationResponseDto(val workOrder:WorkOrderDto,val replayed:Boolean,val correlationId:String)
@Serializable data class WorkTaskMutationResponseDto(val workOrder:WorkOrderDto,val taskId:String,val replayed:Boolean,val correlationId:String)
@Serializable data class WorkDependencyMutationResponseDto(val workOrder:WorkOrderDto,val dependencyId:String,val replayed:Boolean,val correlationId:String)
@Serializable data class WorkTypeChoiceDto(val workType:ConfigRefDto,val description:String?=null,val defaultPriorityCode:String?=null,val defaultProgressWeight:String,val countsTowardProjectProgress:Boolean)
@Serializable data class ProjectActivationResponseDto(val projectId:String,val lifecycleState:String,val version:Long,val replayed:Boolean,val correlationId:String)
